repos:
  - repo: https://github.com/psf/black
    rev: 21.9b0
    hooks:
      - id: black
        language_version: python3
  - repo: local
    hooks:
      - id: sync_doc_requirements
        name: sync_doc_requirements
        entry: poetry export --dev --without-hashes -o docs/requirements.txt -f requirements.txt
        language: python
        pass_filenames: false
        files: 'poetry.lock'
